config/routes.rb
Rails.application.routes.draw do
  root                 'static_pages#home'
  get 'help'        => 'static_pages#help'
  get 'about'       => 'static_pages#about'
  get 'contact'     => 'static_pages#contact'
  get 'signup'      => 'users#new'
  get 'definitions' => 'static_pages#definitions'
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to PhotoEffects"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns full title for pages
  def full_title(page_title = '')
    base_title = 'Cyberbullying'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">

     <%= link_to "Cyberbullying  By Rishabh, Lokesh & Mayank ", root_path, id: "logo1" %> 
       
  <nav>
    <ul>
      
      <li><%= link_to "Contact", contact_path %></li>
       <li><%= link_to "Definitions",   definitions_path %></li>
       </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Cyberbullying", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path, id:"right" %></li>
        <li><%= link_to "About",   about_path, id:"right" %></li>
        <li><%= link_to "Help",   help_path,id:"right" %></li>
              </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>      
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/Rishabh.html.erb
<% provide(:title, "Developers") %>
 <div class="bg"></div>
<div class="jumbotron">
<h1>Rishabh</h1>
This page is under Development
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
 <div class="bg"> </div>
<div class="jumbotron">
<h1>About</h1>
<h2></h2>
<p>
  This the about page of Cyberbullying
</p></h2>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
 <div class="bg"> </div>
<div class="jumbotron">
<h1>Contact</h1>
<h2></h2>
<p>
  Contact Rishabh for any queries what so ever.
</p></h2>
</div>

app/views/static_pages/definitions.html.erb
<% provide(:title, "Definitions") %>
 <div class="bg"> </div>
<div class="jumbotrond">
    
    
<h1>Definitions</h1>

<h2>What is Cyberbullying?</h2>
<div class="p1">
  <p>1) Cyberbullying is bullying that takes place using electronic technology. Electronic technology includes devices and equipment such as cell phones,
    computers, and tablets as well as communication tools including social media sites, text messages, chat, and websites.
Examples of cyberbullying include mean text messages or emails, rumors sent by email or posted on social networking sites, and embarrassing pictures,
videos, websites, or fake profiles.</p> <p>

2) Cyberbullying is the use of cell phones, instant messaging, e-mail, chat rooms or social networking sites such as Facebook and Twitter to harass, threaten 
or intimidate someone. Cyberbullying is often done by children, who have increasingly early access to these technologies. The problem is compounded by the fact
that a bully can hide behind an electronic veil, disguising his or her true identity. This secrecy makes it difficult to trace the source and encourages bullies
to behave more aggressively than they might face-to-face.</p> <p>

3) Cyberbullying can include such acts as making threats, sending provocative insults or racial or ethnic slurs, gay bashing, attempting to infect the victim's 
computer with a virus, and flooding an e-mail inbox with messages. If you are a victim, you can deal with cyberbullying to some extent by limiting computer connection 
time, not responding to threatening or defamatory messages, and never opening e-mail messages from sources you do not recognize or from known sources of unwanted communications.
More active measures include blacklisting or whitelisting e-mail accounts, changing e-mail addresses, changing ISPs, changing cell phone accounts, and attempting to trace the 
source.
Because the use of mobile and online communications has grown so rapidly and the crime is relatively new, many jurisdictions are deliberating over cyberbullying laws. However,
the crime is covered by existing laws against personal threats and harassment. In some cases, it may be advisable to inform the local police department or consult an attorney.
It is not recommended that you retaliate in kind because such behavior can lead to heightened attacks, or even civil actions or criminal charges against you.
</p> <p>
4) Cyberbullying is bullying that takes place using electronic technology. Electronic technology includes devices and equipment such as cell phones, computers, and tablets
as well as communication tools including social media sites, text messages, chat, and websites.
Examples of cyberbullying include mean text messages or emails, rumors sent by email or posted on social networking sites, and embarrassing pictures, videos, websites, or 
fake profiles.</p> 
</div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
 <div class="bg"> </div>
<div class="jumbotron">
<h1>Help</h1>
<p>
  Get help on Cyberbullying.
</p>
</div>

app/views/static_pages/home.html.erb
 <div class="bg"></div>
<div class="jumbotron">
 <h1> Welcome to Cyberbullying</h1> 

<div class="slider">
			<div class="image-slider-wrapper">
				<ul id="image_slider">
					<li><img src="https://dl.dropboxusercontent.com/u/65639888/image/1.jpg"></li>
					<li><img src="https://dl.dropboxusercontent.com/u/65639888/image/4.jpg"></li>
					<li><img src="https://dl.dropboxusercontent.com/u/65639888/image/5.jpg"></li>
					<li><img src="https://dl.dropboxusercontent.com/u/65639888/image/1.jpg"></li>
					<li><img src="https://dl.dropboxusercontent.com/u/65639888/image/4.jpg"></li>
					<li><img src="https://dl.dropboxusercontent.com/u/65639888/image/5.jpg"></li>
				</ul> 		
				
<div id="b1">
<%= link_to "Read More", root_path , class:"btn btn-default" %>
</div>

<div class="pager">
	<h2>What is Cyberbullying?</h2>
<h4>	Cyberbullying is bullying that takes place using electronic technology. Electronic technology includes devices and equipment such as cell phones, computers, 
	and tablets as well as communication tools including social media sites, text messages, chat, and websites.
Examples of cyberbullying include mean text messages or emails, rumors sent by email or posted on social networking sites, and embarrassing pictures, videos, websites, or fake profiles. </h4>
	
	</div>
				</div>
			</div>
	</div>


    
      

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>